### ISSUE TITLE
Crash 1.19.2

### ISSUE THREAD

**Issue by hammertater** [hammertater/treeplant#11]
```
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:74) ~[?:?]
	at net.minecraft.class_3204.method_15892(class_3204.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_16155(class_3215.java:283) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_14134(class_3215.java:221) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_12121(class_3215.java:138) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8402(class_1937.java:197) ~[client-intermediary.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8497(class_1937.java:191) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8320(class_1937.java:369) ~[client-intermediary.jar:?]
	at net.minecraft.class_1750.<init>(class_1750.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_1750.<init>(class_1750.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_1747.handler$zzl000$porting_lib_base$port_lib$useOn(class_1747.java:524) ~[client-intermediary.jar:?]
	at net.minecraft.class_1747.method_7884(class_1747.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.method_7981(class_1799.java:264) ~[client-intermediary.jar:?]
	at ht.treeplant.server.util.PlantUtil.tryToPlant(PlantUtil.java:18) ~[TreePlant-1.19.2-fabric-0.3.1.jar:?]
	at ht.treeplant.server.event.AutoPlant.plantOnDespawn(AutoPlant.java:69) ~[TreePlant-1.19.2-fabric-0.3.1.jar:?]
	at ht.treeplant.server.event.AutoPlantFabric.lambda$init$2(AutoPlantFabric.java:49) ~[TreePlant-1.19.2-fabric-0.3.1.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents.lambda$static$2(ServerEntityEvents.java:69) ~[fabric-lifecycle-events-v1-2.2.4+1b46dc7890-133bf64273a18fad.jar:?]
	at net.minecraft.class_3218$class_5526.handler$zok000$fabric-lifecycle-events-v1$invokeEntityUnloadEvent(class_3218.java:1703) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218$class_5526.method_31437(class_3218.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218$class_5526.method_31797(class_3218.java:1538) ~[client-intermediary.jar:?]
	at net.minecraft.class_5579.method_31850(class_5579.java:221) ~[client-intermediary.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.class_5579.method_31825(class_5579.java:255) ~[client-intermediary.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177) ~[?:?]
	at java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:183) ~[?:?]
	at java.util.Spliterators$LongIteratorSpliterator.forEachRemaining(Spliterators.java:2046) ~[?:?]
	at java.util.Spliterator$OfLong.forEachRemaining(Spliterator.java:775) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.class_5579.method_31816(class_5579.java:241) ~[client-intermediary.jar:?]
	at net.minecraft.class_5579.method_31815(class_5579.java:227) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_31414(class_3898.java:1320) ~[client-intermediary.jar:?]
	at net.minecraft.class_3193.method_31408(class_3193.java:388) ~[client-intermediary.jar:?]
	at net.minecraft.class_3193.method_14007(class_3193.java:463) ~[client-intermediary.jar:?]
	at net.minecraft.class_3204.method_15891(class_3204.java:132) ~[client-intermediary.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraft.class_3204.method_15892(class_3204.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_16155(class_3215.java:283) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:562) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:279) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Answordy** [comment]
Minecraft 1.19.2
Fabric 0.14.23
Fabric api 0.76.1
TreePlant-1.19.2-fabric-0.3.1.jar

> java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at net.minecraft.class_3204.method_15892(class_3204.java:132)
	at net.minecraft.class_3215.method_16155(class_3215.java:283)
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:562)
	at net.minecraft.class_3215.method_19492(class_3215.java:279)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

> java.lang.IllegalStateException: Entity is already tracked!
	at net.minecraft.class_3898.method_18701(class_3898.java:1194)
	at net.minecraft.class_3215.method_18755(class_3215.java:477)
	at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1560)
	at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1538)
	at net.minecraft.class_5579.method_31847(class_5579.java:217)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraft.class_5579.method_31825(class_5579.java:257)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177)
	at java.base/java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:183)
	at java.base/java.util.Spliterators$LongIteratorSpliterator.forEachRemaining(Spliterators.java:2046)
	at java.base/java.util.Spliterator$OfLong.forEachRemaining(Spliterator.java:775)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraft.class_5579.method_31816(class_5579.java:241)
	at net.minecraft.class_5579.method_31815(class_5579.java:227)
	at net.minecraft.class_3898.method_31414(class_3898.java:1320)
	at net.minecraft.class_3193.method_31408(class_3193.java:388)
	at net.minecraft.class_3193.method_14007(class_3193.java:463)
	at net.minecraft.class_3204.method_15891(class_3204.java:132)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_3204.method_15892(class_3204.java:132)
	at net.minecraft.class_3215.method_16155(class_3215.java:283)
	at net.minecraft.class_3215.getChunkBlocking(class_3215.java:1715)
	at net.minecraft.class_3215.method_12121(class_3215.java:1677)
	at net.minecraft.class_1937.method_8402(class_1937.java:197)
	at net.minecraft.class_1937.method_8497(class_1937.java:6078)
	at net.minecraft.class_1937.method_8320(class_1937.java:6570)
	at net.minecraft.class_1750.<init>(class_1750.java:32)
	at net.minecraft.class_1750.<init>(class_1750.java:25)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:264)
	at ht.treeplant.server.util.PlantUtil.tryToPlant(PlantUtil.java:18)
	at ht.treeplant.server.event.AutoPlant.plantOnDespawn(AutoPlant.java:69)
	at ht.treeplant.server.event.AutoPlantFabric.lambda$init$2(AutoPlantFabric.java:49)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents.lambda$static$2(ServerEntityEvents.java:69)
	at net.minecraft.class_3218$class_5526.handler$cnc000$fabric-lifecycle-events-v1$invokeEntityUnloadEvent(class_3218.java:1703)
	at net.minecraft.class_3218$class_5526.method_31437(class_3218.java)
	at net.minecraft.class_3218$class_5526.method_31797(class_3218.java:1538)
	at net.minecraft.class_5579.method_31850(class_5579.java:221)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraft.class_5579.method_31825(class_5579.java:255)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177)
	at java.base/java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:183)
	at java.base/java.util.Spliterators$LongIteratorSpliterator.forEachRemaining(Spliterators.java:2046)
	at java.base/java.util.Spliterator$OfLong.forEachRemaining(Spliterator.java:775)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraft.class_5579.method_31816(class_5579.java:241)
	at net.minecraft.class_5579.method_31815(class_5579.java:227)
	at net.minecraft.class_3898.method_31414(class_3898.java:1320)
	at net.minecraft.class_3193.method_31408(class_3193.java:388)
	at net.minecraft.class_3193.method_14007(class_3193.java:463)
	at net.minecraft.class_3204.method_15891(class_3204.java:132)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_3204.method_15892(class_3204.java:132)
	at net.minecraft.class_3215.method_16155(class_3215.java:283)
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:562)
	at net.minecraft.class_3215.method_19492(class_3215.java:279)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
